Traveler/Models/Place.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Traveler.Models
{
    public class Place
    {
        public int PlaceID { get; set; }

        [Required]
        public int CityID { get; set; }
        public virtual City City { get; set; }

        [Required]
        public int TravelID { get; set; }
        public virtual Travel Travel { get; set; }

        [Display(Name = "Nazwa")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Opis")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public virtual List<Photo> Photos { get; set; }
    }
}

Traveler/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class CitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            var cities = db.Cities.Include(c => c.Country);
            return View(cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CityID,Name,CountryID")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index","Travels");
            }

            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return RedirectToAction("Index", "Home"); ;
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CityID,Name,CountryID")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult ByCountry(int id)
        {
            List<City> cities = db.Cities.Where(c => c.CountryID == id).Include(c => c.Country).ToList();
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class PhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Photos/Create?placeID=1
        public ActionResult Create(int placeID)
        {
            Place place = db.Places.Find(placeID);
            ViewBag.PlaceID = place.PlaceID;
            ViewBag.PlaceName = place.Name;

            return View();
        }
  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PhotoID,FileName,Description,PlaceID")] Photo photo, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                string dirPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "uploads");
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }

                // Nazwa pliku jest wygenerowana przez Guid.NewGuid() i wpisana do ukrytego inputa w formularzu Create.cshtml
                photo.FileName = photo.FileName + Path.GetExtension(file.FileName);

                string filePath = Path.Combine(dirPath, photo.FileName);
                FileStream writeStream = new FileStream(filePath, FileMode.Create);
                BinaryWriter bw = new BinaryWriter(writeStream);
                byte[] buff = new byte[file.ContentLength];
                file.InputStream.Read(buff, 0, file.ContentLength);
                bw.Write(buff);
                bw.Close();

                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Details", "Places", new { id = photo.PlaceID });
            }

            return Create(photo.PlaceID);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }

            return View(photo);
        }

        // POST: Photos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PhotoID,FileName,Description,PlaceID")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Places", new { id = photo.PlaceID });
            }
            ViewBag.PlaceID = new SelectList(db.Places, "PlaceID", "Name", photo.PlaceID);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Details", "Places", new { id = photo.PlaceID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    
    public class PlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        public ActionResult Show(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Create?travelID=1
        public ActionResult Create(int travelID)
        {
            Travel travel = db.Travels.Find(travelID);
            
            ViewData["Country"] = new SelectList(db.Countries.ToList(), "CountryID", "Name");

            ViewBag.TravelID = travel.TravelID;
            ViewBag.TravelName = travel.Name;

            return View();
        }

        // POST: Places/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaceID,CityID,TravelID,Name,Description")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Details", "Travels", new { id = place.TravelID });
            }
            return Create(place.TravelID);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaceID,CityID,TravelID,Name,Description")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = place.PlaceID });
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Details", "Travels", new { id = place.TravelID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Views/Places/Create.cshtml
@model Traveler.Models.Place

@{
    ViewBag.Title = "Dodaj miejsce";
}

<h2>Dodaj miejsce</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="Travel" class="control-label col-md-2">Podróż</label>
            <div class="col-md-10" style="padding-top: 7px;">
                <a href="@Url.Action("Details", "Travels", new { id = ViewBag.TravelID })">@ViewBag.TravelName</a>
                <input type="hidden" value="@ViewBag.TravelID" name="TravelID" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="Country" class="control-label col-md-2">Państwo</label>
            <div class="col-md-10">
                @Html.DropDownList("Country", null, htmlAttributes: new { @class = "form-control", @onchange = "onCountrySelect(this.value)" })
                <a href="@Url.Action("Create", "Countries") ">Dodaj brakujące państwo</a>
            </div>
        </div>

        <div id="citiesFormGroup" class="form-group">
            <label for="City" class="control-label col-md-2">Miasto</label>
            <div class="col-md-10">
                <select id="City" name="CityID" class="form-control"></select>
                <a href="@Url.Action("Create", "Cities") ">Dodaj brakujące miasto</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a class="btn btn-default" href="@Url.Action("Details", "Travels", new { id = ViewBag.TravelID })">Anuluj</a>
            </div>
        </div>
    </div>
}

<script>
    var countryId = $("#Country").val();
    var cities = [];

    if (countryId) {
        onCountrySelect(countryId);
    }

    function onCountrySelect(countryID) {
       $('#City').empty();

        $.ajax('/Cities/ByCountry/' + countryID).done(function (data) {
            cities = data;
            for (var i = 0; i < data.length; i++) {
                appendOptionToCitiesSelect(data[i].CityID, data[i].Name);
            }
        });
    }

    function appendOptionToCitiesSelect(id, name) {
        $('#City').append('<option value="' + id + '">' + name + '</option>');
    }

    var selDiv = "";

    document.addEventListener("DOMContentLoaded", init, false);

    function init() {
        document.querySelector('#file').addEventListener('change', handleFileSelect, false);
        selDiv = document.querySelector(".selectedFiles");
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Traveler/Views/Places/Delete.cshtml
@model Traveler.Models.Place

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Travel.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Traveler/Views/Places/Details.cshtml
@model Traveler.Models.Place

@{
    ViewBag.Title = "Details";
}


<div class="row">
    <h2 class="col-sm-7">@Html.DisplayFor(model => model.Name)</h2>
    <div class="col-sm-5 toolbar">
        @Html.ActionLink("Dodaj zdjęcie", "Create", "Photos", new { placeID = Model.PlaceID }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.PlaceID }, new { @class = "btn btn-default" })
        @Html.ActionLink("Usuń", "Delete", new { id = Model.PlaceID }, new { @class = "btn btn-default" })
    </div>
</div>
<hr />
<dl class="dl-horizontal">

    <dt>Podróż</dt>
    <dd>
        <a href="@Url.Action("Details", "Travels", new { id = Model.Travel.TravelID })">@Model.Travel.Name</a>
    </dd>

    <dt>Państwo</dt>
    <dd>
        @Html.DisplayFor(model => model.City.Country.Name)
    </dd>

    <dt>Miasto</dt>
    <dd>
        @Html.DisplayFor(model => model.City.Name)
    </dd>

    <dt>@Html.DisplayNameFor(model => model.Description)</dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>

</dl>

@if (Model.Photos.Count == 0)
{
    <div class="alert alert-warning">
        Ta podróż jeszcze nie ma żadnych zdjęć, proszę dodaj je przyciskiem "Dodaj zdjęcie"
    </div>
}
else
{
    <h3>Zdjęcia</h3>
    <hr />
    <div class="row">
        @foreach (var photo in Model.Photos)
        {
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="~/uploads/@photo.FileName">
                    <div class="caption">
                        <h5>@photo.Description</h5>
                        <p>
                            @Html.ActionLink("Edytuj opis", "Edit", "Photos", new { id = photo.PhotoID }, new { @class = "btn btn-default" })
                            @Html.ActionLink("Usuń", "Delete", "Photos", new { id = photo.PhotoID }, new { @class = "btn btn-default" })
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
}

<p>
    <a href="@Url.Action("Details", "Travels", new { id = Model.Travel.TravelID })">Powrót</a>
</p>

Traveler/Views/Places/Edit.cshtml
@model Traveler.Models.Place

@{
    ViewBag.Title = "Edit";
}

<h2>Edycja miejsca</h2>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.PlaceID)
    @Html.HiddenFor(model => model.TravelID)
    @Html.HiddenFor(model => model.CityID)

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                @Html.ActionLink("Anuluj", "Details", new { id = Model.PlaceID }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Traveler/Views/Places/Show.cshtml
@model Traveler.Models.Place

@{
    ViewBag.Title = "Details";
}


<div class="row">
    <h2 class="col-sm-7">@Html.DisplayFor(model => model.Name)</h2>
</div>
<hr />
<dl class="dl-horizontal">

    <dt>Podróż</dt>
    <dd>
        <a href="@Url.Action("Show", "Travels", new { id = Model.Travel.TravelID })">@Model.Travel.Name</a>
    </dd>

    <dt>Państwo</dt>
    <dd>
        @Html.DisplayFor(model => model.City.Country.Name)
    </dd>

    <dt>Miasto</dt>
    <dd>
        @Html.DisplayFor(model => model.City.Name)
    </dd>

    <dt>@Html.DisplayNameFor(model => model.Description)</dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>

</dl>

@if (Model.Photos.Count == 0)
{
    <div class="alert alert-warning">
        Ta podróż jeszcze nie ma żadnych zdjęć, proszę dodaj je przyciskiem "Dodaj zdjęcie"
    </div>
}
else
{
    <h3>Zdjęcia</h3>
    <hr />
    <div class="row">
        <section id="least">
            <ul class="least-gallery">
                @foreach (var photo in Model.Photos)
                {
                    <li>
                        <div class="thumbnail">
                            <img src="~/uploads/@photo.FileName">
                            <div class="caption">
                                <h5>@photo.Description</h5>
                            </div>
                        </div>
                    </li>
                }
             </ul>
         </section>
    </div>
}

<p>
    <a href="@Url.Action("Show", "Travels", new { id = Model.Travel.TravelID })">Powrót</a>
</p>