Traveler/Models/City.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;

namespace Traveler.Models
{
    public class City
    {
        public int CityID { get; set; }
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Display(Name = "Państwo")]
        public int CountryID { get; set; }
        public virtual Country Country { get; set; }
    }
}

Traveler/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Traveler.Models
{
    public class Country
    {
        public int CountryID { get; set; }
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
    }
}

Traveler/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Traveler.Models
{
    public class Search
    {
        public string Query { get; set; }

        public List<Country> Countries { get; set; }

        public List<City> Cities { get; set; }

        public List<UserData> Users = new List<UserData>();
        public List<PlacePhoto> CountriesPhoto = new List<PlacePhoto>();
        public List<PlacePhoto> CitiesPhoto = new List<PlacePhoto>();
    }
    public class PlacePhoto
    {
        public int idPlace { get; set; }
        public Photo photo { get; set; }
    }
   
}

Traveler/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class CitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            var cities = db.Cities.Include(c => c.Country);
            return View(cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CityID,Name,CountryID")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index","Travels");
            }

            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return RedirectToAction("Index", "Home"); ;
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CityID,Name,CountryID")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Name", city.CountryID);
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult ByCountry(int id)
        {
            List<City> cities = db.Cities.Where(c => c.CountryID == id).Include(c => c.Country).ToList();
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class CountriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Countries
        public ActionResult Index()
        {
            return View(db.Countries.ToList());
        }

        // GET: Countries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Countries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CountryID,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("Index", "Travels");
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Countries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CountryID,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    
    public class PlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        public ActionResult Show(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Create?travelID=1
        public ActionResult Create(int travelID)
        {
            Travel travel = db.Travels.Find(travelID);
            
            ViewData["Country"] = new SelectList(db.Countries.ToList(), "CountryID", "Name");

            ViewBag.TravelID = travel.TravelID;
            ViewBag.TravelName = travel.Name;

            return View();
        }

        // POST: Places/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaceID,CityID,TravelID,Name,Description")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Details", "Travels", new { id = place.TravelID });
            }
            return Create(place.TravelID);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaceID,CityID,TravelID,Name,Description")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = place.PlaceID });
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Details", "Travels", new { id = place.TravelID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Traveler/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Search
        public ActionResult Index(string query)
        {
            Search model = new Models.Search {Query = query };
            PlacePhoto place = new PlacePhoto();
            Photo p = new Photo();
            List<ApplicationUser> apList = db.Users.Where(u => u.UserName.Contains(query)).ToList();
            foreach(var i in apList)
            {
                model.Users.Add(i.ToUser());
            }
            model.Countries = db.Countries.Where(c => c.Name.Contains(query)).ToList();
            model.Cities = db.Cities.Where(c => c.Name.Contains(query)).ToList();

            if(model.Countries.Count > 0)
            {
                foreach (var i in model.Countries) {
                    p = db.Photos.Where(e => e.place.City.Country.Name == i.Name).FirstOrDefault();
                    if (p != null)
                    {
                        place.idPlace = i.CountryID;
                        place.photo = p;
                        model.CountriesPhoto.Add(place);
                    }
                }
            }
            if (model.Cities.Count > 0)
            {
                foreach (var i in model.Cities)
                {
                    p = db.Photos.Where(e => e.place.City.Name == i.Name).FirstOrDefault();
                    if (p != null)
                    {
                        place.idPlace = i.CityID;
                        place.photo = p;
                        model.CitiesPhoto.Add(place);
                    }
                }
            }

            return View(model);
        }
        public ActionResult Country(string countryName )
        {
            if(countryName == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            List<Place> places = db.Places.Where(e => e.City.Country.Name == countryName).ToList();
            return View(places);
        }
        public ActionResult City(string cityName)
        {
            if (cityName == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            List<Place> places = db.Places.Where(e => e.City.Name == cityName).ToList();
            return View(places);
        }
    }
}

Traveler/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users/Show/user@example.com
        public ActionResult Show(string id)
        {
            UserViewModel model = new UserViewModel { };

            IQueryable<ApplicationUser> foundUsers = db.Users.Where(u => u.UserName == id);

            if (foundUsers.Count() > 0)
            {
                model.User = foundUsers.First().ToUser();
                model.Travels = db.Travels.Where(t => t.UserID == id).ToList();

                return View(model);
            }

            return View("~/Views/Shared/AccessDeniedError.cshtml");
        }
    }
}

Traveler/Views/Search/City.cshtml
@model IEnumerable<Traveler.Models.Place>
@{
    ViewBag.Title = "City";
}

<h2>Miejsca w miasta @Model.First().City.Name</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Show", "Places", new { id = item.PlaceID })" class="col-sm-4" style="display: block;">
            <div class="thumbnail">

                @if (item.Photos.Count == 0)
                {
                    <div class="no-photo-thumbnail">
                        <img src="~/Content/ic_person_black_48dp_2x.png">
                    </div>
                }
                else
                {
                    <img src="~/uploads/@item.Photos.First().FileName" height="200px" width="350px">
                }

            </div>
            <div class="caption">
                <h4>@item.Name</h4>
            </div>
        </a>
    }
</div>

Traveler/Views/Search/Country.cshtml
@model IEnumerable<Traveler.Models.Place> 
@{
    ViewBag.Title = "Country";
}

<h2>Miejsca w państwie @Model.First().City.Country.Name</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Show", "Places", new { id = item.PlaceID })" class="col-sm-4" style="display: block;">
            <div class="thumbnail">

                @if (item.Photos.Count == 0)
                {
                    <div class="no-photo-thumbnail">
                        <img src="~/Content/ic_person_black_48dp_2x.png">
                    </div>
                }
                else
                {
                    <img src="~/uploads/@item.Photos.First().FileName" height="200px" width="350px">
                }

            </div>
            <div class="caption">
                <h4>@item.Name</h4>
            </div>
        </a>
    }
</div>

Traveler/Views/Search/Index.cshtml
@model Traveler.Models.Search
@{
    ViewBag.Title = "Szukaj";
}

<h2>Wyniki wyszukiwania dla wyrażenia "@Model.Query"</h2>
<hr />
@if (Model.Users.Count > 0)
{
    <h3>Użytkownicy</h3>
    <br />
    <div class="row">
        @foreach (var user in Model.Users)
        {
            <a href="@Url.Action("Show", "Users", new { id = user.Nick })" class="col-sm-4" style="display: block;">
                <div class="thumbnail">
                    
                        @if(user.Avatar.IsEmpty()) {
                    <div class="no-photo-thumbnail">
                        <img src="~/Content/ic_person_black_48dp_2x.png">
                    </div>
                        }
                        else
                        {
                        <img src="~/uploads/@user.Avatar" height="200px" width="350px">
                        }
                   
                </div>
                <div class="caption">
                    <h4>@user.Nick</h4>
                </div>
            </a>
        }
    </div>
}

@if (Model.Countries.Count > 0)
{
    <h3>Państwa</h3>
    <br />
    <div class="row">
        @foreach (var country in Model.Countries)
        {
            <a href="@Url.Action("Country", "Search", new { countryName = country.Name})" class="col-sm-4" style="display: block;">
                <div class="thumbnail">
                  @if(Model.CountriesPhoto.Count>0)
                  { 
                      foreach(var photo in Model.CountriesPhoto)
                        {
                            if(photo.idPlace == country.CountryID)
                            {
                                <img src="~/uploads/@photo.photo.FileName"height="200px" width="350px"> 
                            }
                            else{
                                 <div class="no-photo-thumbnail">
                                    <img src="~/Content/ic_landscape_black_48dp_2x.png" />
                                </div>
                             }
                        }
                  }else 
                  {
                    <div class="no-photo-thumbnail">
                        <img src="~/Content/ic_landscape_black_48dp_2x.png" />
                    </div>
                  }
                </div>
                <div class="caption">
                    <h4>@country.Name</h4>
                </div>
            </a>
        }
    </div>
}

@if (Model.Cities.Count > 0)
{
    <h3>Miasta </h3>
    <br />
    <div class="row">
        @foreach (var city in Model.Cities)
        {
            <a href="@Url.Action("City", "Search", new { cityName = city.Name })" class="col-sm-4" style="display: block;">
                <div class="thumbnail">
                    @if(Model.CitiesPhoto.Count>0){
                        foreach(var photo in Model.CitiesPhoto)
                        {
                            if(photo.idPlace == city.CityID)
                            {
                                 <img src="~/uploads/@photo.photo.FileName" height="200px" width="350px">
                            }
                            else{
                                <div class="no-photo-thumbnail">
                                    <img src="~/Content/ic_landscape_black_48dp_2x.png" />
                                </div>
                            }
                        }
                    }else
                    {
                        <div class="no-photo-thumbnail">
                            <img src="~/Content/ic_landscape_black_48dp_2x.png" />
                        </div>
                    }
                </div>
                <div class="caption">
                    <h4>@city.Name</h4>
                </div>
            </a>
        }
    </div>
}

@if (Model.Users.Count == 0 && Model.Countries.Count == 0 && Model.Cities.Count == 0)
{
    <div class="alert alert-warning">Niestety niczego nie znaleziono :(</div>
}