Traveler/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Traveler.Models
{
    public class Comment
    {
        public int ID { get; set; }
        public int TravelID { get; set; }
        public virtual Travel travel { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }

        public string UserID { get; set; }
        public DateTime Date { get; set; }
    }
}

Traveler/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // POST: Comments/Delete/5

        public ActionResult Delete(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

    }
}

Traveler/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Traveler.Models;

namespace Traveler.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users/Show/user@example.com
        public ActionResult Show(string id)
        {
            UserViewModel model = new UserViewModel { };

            IQueryable<ApplicationUser> foundUsers = db.Users.Where(u => u.UserName == id);

            if (foundUsers.Count() > 0)
            {
                model.User = foundUsers.First().ToUser();
                model.Travels = db.Travels.Where(t => t.UserID == id).ToList();

                return View(model);
            }

            return View("~/Views/Shared/AccessDeniedError.cshtml");
        }
    }
}

Traveler/Views/Shared/AccessDeniedError.cshtml
@{
    ViewBag.Title = "Brak dostępu";
}

<h2 class="text-danger">Brak dostępu</h2>
<p class="text-danger">Nie masz dostępu do tej strony lub szukany obiekt nie został znaleziony</p>

Traveler/Views/Shared/_Comment.cshtml
@model Traveler.Models.ShowTravelViewModel
@using Microsoft.AspNet.Identity
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.comment.TravelID)
    <div class="row">
        <div class="col-md-5">
            <div class="comment-title">
                Komentarze
            </div>
            @{
                if (Model.Comments.Count == 0)
                {
                    <div class="alert alert-warning">
                        Brak komentarzy dla tej podróży
                    </div>
                }
                else
                {
                    foreach (var item in Model.Comments)
                    {
                        <div class="comment-body">

                            <div class="span">
                                (@item.Date.ToString())
                                <a href="@Url.Action("Show", "Users", new { id = item.UserID } )" style="color: #000000;">@item.UserID</a>
                            </div>
                            <p>
                                @item.Text
                            </p>
                           @if (Request.IsAuthenticated && item.UserID == User.Identity.GetUserName())
                           {
                               <a href="@Url.Action("Delete", "Comments", new { id = item.ID })" style="color: #000000;">Usuń</a>
                           }

                        </div>

                    }
                }
            }
        </div>

        <div class="col-md-5">
            @if (Request.IsAuthenticated)
            {
                <div class="comment-add-title">
                    Dodaj komentarz
                </div>
                <div class="comment-add">
                    @Html.EditorFor(model => model.comment.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.comment.Text, "", new { @class = "text-danger" })
                    <input type="submit" value="Dodaj" class="btn-success" />
                </div>
            }
        </div>
    </div>
                }
   

Traveler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Traveler</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/photoswipe.css")
    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/lib/klass.min.js")
    @Scripts.Render("~/Scripts/code.photoswipe-3.0.5.min.js")
   

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Traveler", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Moje podróże", "Index", "Travels")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
                <form class="navbar-form navbar-right hidden-xs" role="search" action="@Url.Action("Index", "Search")">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Szukaj" name="query" style="width: 120px;">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @if (ViewBag.RenderOutsideContainer != null)
    {
        @RenderBody()
    }

    <div class="container body-content">
        @if (ViewBag.RenderOutsideContainer == null)
        {
            @RenderBody()
        }
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Traveler</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>